### ISSUE TITLE
Can't change git repository for bootloader

### ISSUE THREAD

**Issue by boatbodger** [maccoylton/esp-homekit-gosund-up111#2]
I successfully followed the instructions as far as installing bootloader.bin in a UP111 but stupidly entered the wrong git repository name.
I can see from the UDP log that it is forlornly plugging away trying to download updates and partially succeeding, but as soon as it has flashed the firmware, it restarts and repeats the process.
I can get back to the 'settings' page by deliberatly killing the WiFi that it is connecting to, but the /settings page then does not have the option of clearing or correcting the git repository the device will try and ota from.
There must surely be a way of doing this?
I've also struggled to find the source for bootloader.bin - I can't work out who wrote that piece and where its source would be.
Any help you can offer would be most welcome, and thanks for all the work you've done on this.
Chris

**Comment by boatbodger** [comment]
![capture](https://user-images.githubusercontent.com/717022/104821247-71747a00-5832-11eb-91f7-88b1917d8a7a.png)

**Comment by maccoylton** [comment]
The bootloader is mentioned in the Wiki:- https://github.com/HomeACcessoryKid/life-cycle-manager

Set the LedPin, and join your Wifi, then go into emergency mode or factory reset by following the instruction in the "New feature version 2"  of the site mentioned above.

BTW What specifically did you enter ?  There is maybe an alternative way to solve this depending on what you entered.

**Comment by boatbodger** [comment]
I had entered HomeACcessoryKid/ota-demo - which is probably firmware for something completely different!
Anyway, thanks to your tip, I managed (eventually) to factory default the thing.  Along the way, I found that you need to leave it unplugged for a couple of seconds between each power-up - I was doing it too short to start with, I think.
I now have managed to flash the thing with your code. so this point is now closed, and I'll come back on the 'pairing key' difficulty "issue".
Thanks again for your help.

**Comment by maccoylton** [comment]
Good to hear the boot loader did it's job
