### ISSUE TITLE
How to determine HomeKit pairing ID

### ISSUE THREAD

**Issue by boatbodger** [maccoylton/esp-homekit-gosund-up111#3]
I have successfully flashed a UP111 with esp-homekit-gosund-111.
When I try to adopt it in Home Assistant, I am asked for a pairing key of the form xxx-xx-xxx
I notice there is an 8-digit number presented on discovery (in my case UP111-15044096), but entering that - either as 150-44-096 or as 15044096 returns 'incorrect key'
I looked at the source code and saw a key '111-11-111' but that does not work either.
Any chance the "how to" could be updated with where one can find the correct pairing key?

With thanks,
Chris

**Comment by maccoylton** [comment]
>I have successfully flashed a UP111 with esp-homekit-gosund-111. ...

@boatbodger 111-11-111 is the correct code. Did you install the pre-built firmware or build your own?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by boatbodger** [comment]
Thanks for response.
I am using pre-built, and attempting to do all this without involving an AppleTV, which I think I should be able to do, if I understand the Home Assistant documentation correctly.  I do, though,  have an Apple TV on the network.  Could this be interfering with the association pairing?  My knowledge of LAN protocols etc is fairly detailed, but I've not yet found a clear description of the LAN transactions which go on during pairing (I believe Bonjour is used for discovery, but something different for pairing), and I can't get tcpdump to run on the Home Assistant host, so I need to do some fiddling about with mirror ports to see what's going on.

**Comment by maccoylton** [comment]
I've never used Home Assistant, so no knowledge of how it might work or integrate with homekit. 

Have you tried pairing form the Home or Eve App on an IOS device? Does that work?

**Comment by boatbodger** [comment]
I have now tried using Home from an iOS device, and managed to pair one of my devices, and caught a decent wireshark capture, so I now know what *should* happen.
This now definitely seems to be a problem with Home Assistant - but thanks for confirming the pairing code.  That was of course critical.
Footnote for others starting on this journey:  My assessment ofthe trace is that Homekit controller uses MDNS to discover _hap service from device.
Then, over TCP, the controller uses HTTP POST /pair-setup and POST /pair-verify to achieve the pairing, and subsequently control/interrogation.

**Comment by maccoylton** [comment]
Full spec of HAP protocol is available at:- https://developer.apple.com/support/homekit-accessory-protocol/

**Comment by boatbodger** [comment]
Another footnote for others contemplating this journey: I've given up with Home Assistant - at least for the time being.
I'm instead using a node library at https://github.com/mrstegeman/hap-controller-node which works perfectly with a batch of gosund plugs flashed with this repository's firmware binary.   Grateful thanks to @maccoylton and others.
