### ISSUE TITLE
Tuya concert fail on new GoSund UP-111 smart plug

### ISSUE THREAD

**Issue by kevinwebb66** [maccoylton/esp-homekit-gosund-up111#5]
Flashed Tuya-convert to a couple of these successfully last week (twin-pack from Amazon UK). 
4-pack arrived this week, same model but different text on the reverse - Tuya Convert failed and cannot now use the device.  
Later ones contains chip UP111-C (1.0.6) dated 21.01.25, previous ones look identical internally with same chip but earlier date. Suspect later ones may have newer Tuya firmware.

**Comment by maccoylton** [comment]
Checkout the Tuya-convert website. There is new firmware version used on newer devices for which Tuya-convert doesn't work. Apologies there is nothing I can do about this
